### PR TITLE
preferences: Remap macOS keys

### LINKED ISSUE #58: [Mac] Keybinding editor doesn't recognise Command key
#### Steps to reproduce:

1. Go to Preferences -> Keys
2. Select Undo
3. Press Add Key Sequence
4. Press Cmd+Z

#### Expected behaviour:

- Undo would be bound to Cmd+Z

#### Actual behaviour:

- The Cmd (a.k.a. Meta) modifier is not recognised, Undo will just be bound to the `z` key

**Note:** I was about to report a nitpick about the default keybindings not adhering to Mac platform conventions and tried to create and export a keybindings file that could be used as the Mac default when I ran into this issue.

### PR DESCRIPTION
**Pull request by viernullvier**
This PR will remap the PC-based keybindings to align with platform conventions on macOS. `Cmd` will be used instead of `Ctrl`, the non-existent `Alt` key will be replaced with (Mac) `Ctrl`, `Backspace` and `Delete` will be swapped. The remapping allows for a platform-independent default keybinding and makes custom keybindings portable between platforms.

Fixes #58.
Supersedes #59 .

### Scope
- Remap key modifier codes for Cmd (Mac) to Ctrl (PC) and Ctrl (Mac) to Alt (PC) on Mac
- Swap internal key codes for Backspace and Delete on Mac
- Revert the Mac key remapping for display purposes
- Make `key_sequence_item_to_string` use `keyval_to_string` for pretty-printing keys as well

### Out of scope
- Using `Option` as a modifier might not work for non-character keys because it is not configured as a valid modifier key.

### CODE REVIEW

File: src/util/key_util.hpp [hunk 1]
```diff
@@ -0,0 +1,20 @@
+#pragma once
+
+#ifdef __APPLE__
+#define REMAP_KEYS(keyval, state)                                                                                      \
```
Comment (carrotIndustries) [inline src/util/key_util.hpp:4]: I think that'd be better off as a function taking references to keyval and state.

Comment (viernullvier) [reply src/util/key_util.hpp]: Done.

File: src/util/key_util.cpp [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+        state |= Gdk::ModifierType::CONTROL_MASK;
+    }
+    if (keyval == GDK_KEY_BackSpace)
+        keyval = GDK_KEY_Delete;
+    else if (keyval == GDK_KEY_Delete)
+        keyval = GDK_KEY_BackSpace;
+#endif
+}
+
+} // namespace dune3d
```
Comment (ruevs) [inline src/util/key_util.cpp:24]: `C` and `C++` files should end with an empty line. A single line feed (0x0A) as a minimum.

Comment (viernullvier) [reply src/util/key_util.cpp]: Interesting, I assumed that `clang-format` would take care of that, but apparently it did not. Added it.

I'd suggest adding `InsertNewlineAtEOF: true` to `.clang-format`, but this would be a bit out of scope for this PR.
